### ISSUE TITLE
Short window length gives Value Error in Semblance stack

### ISSUE THREAD

**Issue by jwbishop** [uafgeotools/rtm#29]
Using a short window, e.g. 15 seconds, returns a ValueError when semblance is used as the stack function. The waveform looks like it's 30 seconds long. Using a shorter window of ~15 seconds returns a ValueError related to broadcasting.
https://github.com/uafgeotools/rtm/blob/master/rtm/grid.py#L521

**Comment by liamtoney** [comment]
@davidfee5 is this an easy fix? Not too familiar with the code here.

**Comment by liamtoney** [comment]
The default regional example fails during `grid_search()` with a similar (same?) error:
```pytb
    S = grid_search(processed_st=st_proc, grid=grid, time_method=TIME_METHOD,
  File "/Users/ldtoney/repos/rtm/rtm/grid.py", line 525, in grid_search
    dtmp[k, :] = np.hstack((tr.data[nrem:], nrem_zero))
ValueError: could not broadcast input array from shape (1320) into shape (1321)
```
Appears to be a simple indexing error.

**Comment by davidfee5** [comment]
Yes, one of the stations has less samples than the others (1320 vs 1321). This should be fixed in waveform_collection I think. Checking now.

**Comment by davidfee5** [comment]
I think the two issues mentioned here are unrelated. The first one seems like a semblance-related window issue.
