### ISSUE TITLE
Station elevation bug in prepare_fdtd_run()

### ISSUE THREAD

**Issue by liamtoney** [uafgeotools/rtm#30]
In `prepare_fdtd_run()`, `staxyz_g` stores index values and `staxyz` multiplies by the DEM spacing to get physical units. However, the third entry in `staxyz_g`, which is the station elevation from `LOCAL_INFRA_COORDS`, is also multiplied by the DEM spacing, even though it's already in physical units (see line below). This results in erroneously large station elevations being sent to FDTD.

https://github.com/uafgeotools/rtm/blob/4ee89c8be575d73030a71e7f773080eb40ba420d/rtm/travel_time.py#L88

**Comment by davidfee5** [comment]
I'll work on this. Shouldn't cause too many issues as the stations are typically clamped to the DEM elevations during the FDTD simulations.
