### ISSUE TITLE
Station elevations should be clamped to DEM

### ISSUE THREAD

**Issue by davidfee5** [uafgeotools/rtm#33]
For the travel time calculation in 3-D, the station elevations should be clamped to the DEM by default. Right now the DEM elevation may differ than the provided tr.stats.elevation, resulting in an incorrect Euclidean distance and travel-time calculation. This is the default for the FDTD calculation. Might want to provide an option for a floating (e.g. aerostat!) station that is not clamped to the ground.

**Comment by liamtoney** [comment]
As discussed, let's make clamped-to-DEM the default with no option for floating stations — can add this in later if needed.

**Comment by davidfee5** [comment]
Fixed in #34
