### ISSUE TITLE
README missing 'pip install' line for installation

### ISSUE THREAD

**Issue by fkdannemann** [uafgeotools/rtm#69]
sry to be nit-picky :)

**Comment by liamtoney** [comment]
Hmm, I don't see where we're missing a `pip install`. Can you point out where?

**Comment by davidfee5** [comment]
Is this still an issue? Maybe we can close it? thanks

**Comment by liamtoney** [comment]
@fkdannemann closing for now, please comment if you're still having issues and we can sort it out and re-open if needed.
