### ISSUE TITLE
dem reshaping issue

### ISSUE THREAD

**Issue by davidfee5** [uafgeotools/rtm#75]
I now get an error in `produce_dem` in multiple scenarios. The error comes from here: https://github.com/uafgeotools/rtm/blob/d39438e8f954b74a677a5f1ed412ae8eff188e73/rtm/grid.py#L322 and the message looks something like: 
`ValueError: replacement data must match the Variable's shape. replacement data has shape (4542, 2687); Variable has shape (81, 81)`

Possibly related to reshaping using gdal?

**Comment by liamtoney** [comment]
Solution: Use `rioxarray` like in the Fresnel code... PR incoming...
